locale: "en-US"
title: "Casey Crisman-Cox"
name: &name "Casey Crisman-Cox"
description: &description "Assistant Professor of Political Science at Texas A&M University"
tagline: "Casey Crisman-Cox's research page. political science. international relations. EITM. statistical methods."
github:
  url: "ccrismancox.github.io"
  is_project_page: "false"
remote_theme: pages-themes/cayman@v0.2.0
baseurl: ""
repository: "ccrismancox/ccrismancox.github.io"
google_analytics: UA-65611146-2
words_per_minute: 160
twitter: 
  username: "ccrismancox"
# Site Author and information
author:
  name             : "Casey Crisman-Cox"
  avatar           : 
  bio              : "Assistant Professor"
  location         : 
  employer         :
  pubmed           :
  orcid            : "http://orcid.org/0000-0002-5229-3955"
  googlescholar    : "https://scholar.google.com/citations?user=bAGzLCgAAAAJ"
  email            : 
  uri              :
  bitbucket        : "ccrismancox"
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ccrismancox"
  gitlab           : 
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         : "caseycrismancox"
  pinterest        :
  soundcloud       :
  stackoverflow    : "https://stackoverflow.com/users/14270942/ccrismancox"
  steam            :
  tumblr           :
  twitter          : "ccrismancox"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag
gems:
  - jekyll-seo-tag

