title: "Casey Crisman-Cox"
name: &name "Casey Crisman-Cox"
locale                   : "en-US"
description: ""
remote_theme: pages-themes/cayman@v0.2.0
twitter: &username "ccrismancox"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
