# site settings
locale: "en-US"
title: "Casey Crisman-Cox Political Scientist"
title_separator          : "-"
name                     : &name "Casey Crisman-Cox"
description              : &description "Casey Crisman-Cox Professional Website"
url                      : https://ccrismancox.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" 
repository               : "ccrismancox/ccrismancox.github.io"
teaser                   : 
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add
theme: jekyll-theme-cayman
