title: "Casey Crisman-Cox"
name: &name "Casey Crisman-Cox"
locale                   : "en-US"
description: ""
remote_theme: pages-themes/cayman@v0.2.0
author:
    name: Casey Criman-Cox
    email: ccrismancox@gmail.com
    github: ccrismancox
    twitter: ccrismancox
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo